#spring:
#  cloud:
#    alicloud:
#      access-key: LTAIdKJjoKz6G1U3
#      secret-key: COoXw2r48L8wHPoWL1hMyRGdy2PZNCH
#      oss:
#        endpoint: oss-cn-shanghai.aliyuncs.com
#        bucket: qiyuesuo-dev
#
#server:
#  port: 11100
#
#
#logging:
#  level:
#    c
